In [1]:
import pandas as pd 

In [2]:
import numpy as np

In [3]:
from tensorflow.keras.datasets import mnist

In [4]:
(Xtrain, ytrain), (Xtest, ytest) = mnist.load_data()

In [5]:
Xtrain.shape

(60000, 28, 28)

In [6]:
Xtest.shape

(10000, 28, 28)

In [7]:
ytrain.shape

(60000,)

In [8]:
ytest.shape

(10000,)

In [10]:
Xtrain

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [9]:
Xtrain[12]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,  12,  99,  91, 142, 155, 246, 182, 155, 155, 155,
        155, 131,  52,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [11]:
Xtrain.max()

255

In [12]:
Xtrain.min()

0

In [13]:
Xtrain_scale = Xtrain/255.0

In [15]:
Xtrain_scale[12]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [16]:
Xtest_scale  = Xtest/255.0

In [18]:
Xtest[9]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [19]:
Xtest_scale[12]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

###  Functional  Model Building

In [20]:
from tensorflow.keras.models import Model

In [21]:
from tensorflow.keras.layers import Input, Flatten, Dense

In [22]:
Xtrain.shape

(60000, 28, 28)

In [23]:
feed = Input(shape=(28,28))

In [24]:
flat = Flatten()(feed)

In [25]:
dh1 = Dense(32, activation = "relu")(flat)

In [26]:
dh2 = Dense(64, activation = 'relu')(dh1)

In [27]:
dh3 = Dense(32, activation = 'relu')(dh2)

In [28]:
out = Dense(10, activation = 'softmax')(dh3)

In [29]:
model = Model(inputs = feed, outputs = out )

In [30]:
model.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy", metrics = ['accuracy'])

In [31]:
model.fit(Xtrain_scale, ytrain, epochs= 20)

Epoch 1/20
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3340 - accuracy: 0.9025
Epoch 2/20
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1512 - accuracy: 0.9544
Epoch 3/20
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1167 - accuracy: 0.9638
Epoch 4/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0943 - accuracy: 0.9707
Epoch 5/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0836 - accuracy: 0.9743
Epoch 6/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0748 - accuracy: 0.9764
Epoch 7/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0657 - accuracy: 0.9793
Epoch 8/20
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0592 - accuracy: 0.9807
Epoch 9/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0547 - accuracy: 0.9822
Epoch 10/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.051

In [32]:
model.evaluate(Xtest_scale,ytest)

313/313 [==============================] - 1s 2ms/step - loss: 0.1421 - accuracy: 0.9674


[0.1420666128396988, 0.9674000144004822]